#!/bin/sh

BACKUP_LOCAL=${BACKUP_LOCAL:-/data}
BACKUP_PATH=${BACKUP_PATH:-/backup}
BACKUP_COMPRESS="${BACKUP_COMPRESS:-false}"
BACKUP_PASSWORD="${BACKUP_PASSWORD:-password}"
BACKUP_NAME="${BACKUP_NAME:-localhost}"
BACKUP_HOURLY="${BACKUP_HOURLY:-0}"
BACKUP_DAILY="${BACKUP_DAILY:-3}"
BACKUP_WEEKLY="${BACKUP_WEEKLY:-3}"
BACKUP_MONTHLY="${BACKUP_MONTHLY:-3}"
BACKUP_YEARLY="${BACKUP_YEARLY:-3}"
IS_REMOTE=$([ -z "$BACKUP_SOURCE" ] && echo "false" || echo "true")
BACKUP_SOURCE=${BACKUP_SOURCE:-$BACKUP_LOCAL}
